PRN231/lab/lab3/Prn231-Lab3-main2/WebClient/Models/Address.cs
namespace WebClient.Models
{
    public class Address
    {
        public string City { get; set; }
        public string Street { get; set; }
    }
}

PRN231/lab/lab3/Prn231-Lab3-main2/WebClient/Models/BookModel.cs
namespace WebClient.Models
{
    public class BookModel
    {
        public int? Id { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public decimal Price { get; set; }
        public Address Location { get; set; }
        public int PressId { get; set; }
        public PressModel Press { get; set; }
    }
}

PRN231/lab/lab3/Prn231-Lab3-main2/WebClient/Models/ErrorViewModel.cs
namespace WebClient.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PRN231/lab/lab3/Prn231-Lab3-main2/WebClient/Models/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebClient.Models
{
    public class LoginModel
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Email is Empty")]
        public string Username { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is Empty")]
        public string Password { get; set; }
    }
}

PRN231/lab/lab3/Prn231-Lab3-main2/WebClient/Models/PressModel.cs
namespace WebClient.Models
{
    public enum Category
    {
        Book,
        Magazine,
        EBook
    }
    public class PressModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Category Category { get; set; }
    }
}

PRN231/lab/lab3/Prn231-Lab3-main2/WebClient/Models/UserModel.cs
namespace WebClient.Models
{
    public enum Role
    {
        Admin, User
    }
    public class UserModel
    {
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Role Role { get; set; }
    }
}

PRN231/lab/lab3/Prn231-Lab3-main2/WebClient/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
    public class BookController : Controller
    {
        public BookController()
        {
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            return View();
        }
    }
}

PRN231/lab/lab3/Prn231-Lab3-main2/WebClient/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebClient.Models;

namespace WebClient.Controllers
{
    public class LoginController : Controller
    {
        public LoginController()
        {
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PRN231/lab/lab3/Prn231-Lab3-main2/WebClient/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
    public class RegisterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PRN231/lab/lab3/Prn231-Lab3-main2/WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStoreODataAjax</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebClient.styles.css" asp-append-version="true" />

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/smoothness/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid ">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="Index">BookStoreODataAjax</a>
                <button class="nav-link text-white btn-danger" onclick="LogOut()">Log Out</button>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between align-content-end">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-danger">Log Out</a>
                        </li>
                    </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookStoreODataAjax - By Huyltse151262@fpt.edu.vn
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script type="text/javascript" >
        var token = sessionStorage.getItem("token")
        if (!token){
            window.location.href = '/';
        }

        function LogOut(){
            sessionStorage.clear();
            window.location.href = '/';
        }
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PRN231/lab/lab3/Prn231-Lab3-main2/WebClient/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang ="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStoreODataAjax</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/smoothness/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

</head>
<body>
    <header class="fixed-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index">BookStoreODataAjax</a>
            </div>
        </nav>
    </header>
    <div class="container">
    <main role="main" class="pb-3">
    @RenderBody()
    </main>
    </div>


    <footer class="border-top footer text-muted ">
        <div class="container">
            &copy; 2023 - BookStoreODataAjax - By Huyltse151262@fpt.edu.vn
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>